[package]
name = "ingrid"
version = "0.1.0"
authors = ["Eric"]
edition = "2018"

[dependencies]
warp = "0.2"
parking_lot = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }

[[bin]]
name = "ingrid"
path = "src/main.rs"