version: '3.7'

services:
    server-rust:
        image: ulhacks/ingrid-backend-rust:latest
        # specify specific ports we want to use here:
        ports:
            - 8080:8080
        entrypoint:
            - cargo
            - run
            - server
    server-go:
        image: ulhacks/ingrid-backend-go:latest
        # specify specific ports to use:
        command:
            - /go/bin/app
            - server
        ports:
            - 8081

    server-node:
        image: ulhacks/ingrid-backend-node:latest
        # todo: daniel figure stuff out here
        ports:
            - 8079:8079
        entrypoint:
            # todo: daniel, add in what you would do, ie npm start, etc.
            - npm
            - run
            - watch
    
    authn:
        image: ulhacks/ingrid-backend-go:latest
        # specify specific ports to use:
        command:
            - /go/bin/app
            - authn
        ports:
            - 8082
    
    provider_discovery:
        image: ulhacks/ingrid-backend-go:latest
        command:
            - /go/bin/app
            - provider_discovery
        ports:
            - 8083
    
    providers-rust:
        image: ulhacks/ingrid-backend-rust:latest
        entrypoint:
            - cargo
            - run
            - providers
        ports:
            - 8084

    providers-go:
        image: ulhacks/ingrid-backend-go:latest
        command:
            - /go/bin/app
            - provider
        ports:
            - 8085

    # frontend: