version: '3.7'

services:
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
     - 6379:6379
    volumes:
     - redis-data:/redis-data
  
volumes:
  db-data:
  redis-data: